version: "3.3"

services:
  
  backend:
    container_name: backend
    networks:
      - tahouse
    build:
      context: ../
      dockerfile: local/Dockerfile.local
    env_file:
      - .env
    ports:
      - 3001:3001

networks:
  tahouse:
    name: tahouse
    external: true
